Logger/glm: accept Logger as a universal reference
Fixes the following compilation error:
`candidate function template not viable: expects an lvalue for 1st argument`

For the cases like:

```cpp
glm::vec3 test {1, 2, 3};
Log::debug("Test") << test << Log::endl;
                   ^^
             error was here
```