Fixed compilation error under Windows
Nvidia error: error C0000: syntax error, unexpected ',', expecting ';'
at token ","
Intel error: ERROR: 0:67: 'structure' : Only floating point, integer or
opaque type declaration can have the type preceded by a precision
qualifier. Unacceptable type

Under Linux everything compiles fine.

So, instead of
uniform struct Foo {
    ...
}, bar[N];
must be
uniform struct Foo {
    ...
} bar[N];